ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_seq');
ALTER TABLE credentials ALTER COLUMN id SET DEFAULT nextval('credentials_seq');
ALTER TABLE ingredient ALTER COLUMN id SET DEFAULT nextval('ingredient_seq');

INSERT INTO users(name, surname, email)VALUES('Admin', 'Root', 'admin@mail.com');

INSERT INTO credentials(username, password, role, user_id)VALUES('admin', '$2a$10$zXfQs9TdcOamfi6oBuKZqu8miF/LV93/CwqBlRdNWR8yRdsd14I1i', 'ADMIN', 1);

INSERT INTO ingredient(name)VALUES('salt');
INSERT INTO ingredient(name)VALUES('olive oil');
INSERT INTO ingredient(name)VALUES('avocado');
INSERT INTO ingredient(name)VALUES('chicken wings');
INSERT INTO ingredient(name)VALUES('chicken breast');
INSERT INTO ingredient(name)VALUES('tomato');
INSERT INTO ingredient(name)VALUES('tomato sauce');
INSERT INTO ingredient(name)VALUES('tuna');
INSERT INTO ingredient(name)VALUES('sugar');
INSERT INTO ingredient(name)VALUES('flour');
INSERT INTO ingredient(name)VALUES('eggs');
INSERT INTO ingredient(name)VALUES('cheese');
INSERT INTO ingredient(name)VALUES('mozzarella');
INSERT INTO ingredient(name)VALUES('rigatoni');
INSERT INTO ingredient(name)VALUES('spaghetti');
INSERT INTO ingredient(name)VALUES('yeast');
INSERT INTO ingredient(name)VALUES('pepper');
INSERT INTO ingredient(name)VALUES('salame');
INSERT INTO ingredient(name)VALUES('ham');
INSERT INTO ingredient(name)VALUES('jam');
INSERT INTO ingredient(name)VALUES('baking powder');
INSERT INTO ingredient(name)VALUES('potato');
INSERT INTO ingredient(name)VALUES('rice');
INSERT INTO ingredient(name)VALUES('carrots');
INSERT INTO ingredient(name)VALUES('beef');
INSERT INTO ingredient(name)VALUES('celery');
INSERT INTO ingredient(name)VALUES('cinnamon');
INSERT INTO ingredient(name)VALUES('noodles');
INSERT INTO ingredient(name)VALUES('onions');
INSERT INTO ingredient(name)VALUES('garlic');
INSERT INTO ingredient(name)VALUES('ginger');
INSERT INTO ingredient(name)VALUES('honey');
INSERT INTO ingredient(name)VALUES('vinegar');
INSERT INTO ingredient(name)VALUES('salciccia');
INSERT INTO ingredient(name)VALUES('eggplant');
INSERT INTO ingredient(name)VALUES('pineaple');
INSERT INTO ingredient(name)VALUES('sweet pepper');
INSERT INTO ingredient(name)VALUES('bacon');
INSERT INTO ingredient(name)VALUES('guanciale');
INSERT INTO ingredient(name)VALUES('prosciutto cotto');
INSERT INTO ingredient(name)VALUES('prosciutto crudo');
INSERT INTO ingredient(name)VALUES('pecorino');
INSERT INTO ingredient(name)VALUES('parmigiano');
INSERT INTO ingredient(name)VALUES('oregan');
INSERT INTO ingredient(name)VALUES('minced meat');
INSERT INTO ingredient(name)VALUES('butter');
INSERT INTO ingredient(name)VALUES('lemon juice');
INSERT INTO ingredient(name)VALUES('whipping cream');
INSERT INTO ingredient(name)VALUES('basil');
INSERT INTO ingredient(name)VALUES('lettuce');
INSERT INTO ingredient(name)VALUES('red beans');